const { ImapFlow } = require('imapflow');
const { simpleParser } = require('mailparser');
const { processInboundEmail } = require('./inboundEmailService');
const { db } = require('../config/store');
const env = require('../config/env');

// Same UID high-water-mark polling pattern as the SuperSpeech backend.
const POLL_INTERVAL_MS = parseInt(env.IMAP_POLL_INTERVAL_MS) || 120000;
const OWN_ADDRESS = (env.EMAIL_FROM || 'products@williamsquantum.com').toLowerCase();

const SKIP_SENDER_PATTERNS = [
  'mailer-daemon', 'postmaster', 'no-reply', 'noreply', 'no_reply',
  'notifications@', 'notify@', 'auto-confirm', 'automated',
  'donotreply', 'bounce', 'newsletter'
];

let timer = null;
let polling = false;

function senderAddress(parsedFrom) {
  if (!parsedFrom) return '';
  const addr = (parsedFrom.value || []).map(a => (a.address || '').toLowerCase()).join(' ');
  return addr || (parsedFrom.text || '').toLowerCase();
}

function shouldSkip(fromAddr) {
  if (!fromAddr) return true;
  if (fromAddr.includes(OWN_ADDRESS)) return true;
  return SKIP_SENDER_PATTERNS.some(p => fromAddr.includes(p));
}

async function getLastUid() {
  try {
    const doc = await db.collection('config').doc('imapState').get();
    return doc.exists ? doc.data().lastUid || 0 : null;
  } catch { return null; }
}

async function setLastUid(uid) {
  try {
    await db.collection('config').doc('imapState')
      .set({ lastUid: uid, updatedAt: new Date().toISOString() }, { merge: true });
  } catch (e) { console.warn('imap state write failed:', e.message); }
}

async function pollOnce() {
  if (polling) return;
  polling = true;

  const client = new ImapFlow({
    host: env.IMAP_HOST || 'mail.spacemail.com',
    port: parseInt(env.IMAP_PORT) || 993,
    secure: true,
    auth: {
      user: env.EMAIL_USER,
      pass: env.EMAIL_PASSWORD
    },
    tls: { rejectUnauthorized: false },
    logger: false
  });

  try {
    await client.connect();
    const lock = await client.getMailboxLock('INBOX');
    try {
      let lastUid = await getLastUid();

      if (lastUid === null) {
        const all = await client.search({ all: true }, { uid: true }) || [];
        const max = all.length ? Math.max(...all) : 0;
        await setLastUid(max);
        console.log(`IMAP poller seeded at UID ${max} (${all.length} existing messages skipped)`);
        return;
      }

      // RFC 3501 quirk: "uid N:*" ALWAYS returns the mailbox's last message,
      // even when N exceeds its UID. Without this filter the same tail
      // message would be re-processed (and re-replied to) every poll forever.
      const found = await client.search({ uid: `${lastUid + 1}:*` }, { uid: true }) || [];
      const uids = found.filter(u => u > lastUid);
      for (const uid of uids) {
        const msg = await client.fetchOne(uid, { source: true }, { uid: true });
        if (!msg || !msg.source) { await setLastUid(uid); continue; }

        const parsed = await simpleParser(msg.source);
        const fromAddr = senderAddress(parsed.from);

        const autoSubmitted = (parsed.headers.get('auto-submitted') || '').toString().toLowerCase();
        const isAutoGenerated = autoSubmitted && autoSubmitted !== 'no';

        // Self-mail is skipped UNLESS it's the principal answering an agent
        // approval request - that's the contract gate / draft approval path.
        const selfAgentReply = fromAddr.includes(OWN_ADDRESS)
          && /re:\s*\[wq agent\]/i.test(parsed.subject || '');
        const approverReply = /re:\s*\[wq agent\]/i.test(parsed.subject || '');
        if ((shouldSkip(fromAddr) && !selfAgentReply && !approverReply) || isAutoGenerated) {
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          await setLastUid(uid);
          continue;
        }

        try {
          await processInboundEmail({
            from: fromAddr,
            subject: parsed.subject || '',
            text: parsed.text || '',
            html: typeof parsed.html === 'string' ? parsed.html : ''
          });
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          await setLastUid(uid);
          console.log('Processed inbound email from:', fromAddr);
        } catch (err) {
          // ALWAYS advance past a failed message: processInboundEmail sends its
          // reply mid-flow, so a throw after the send must not re-trigger it.
          // Dead-letter the failure to agentActions for manual review instead
          // of re-processing (and re-emailing) every poll cycle forever.
          console.error('Failed to process inbound email from', fromAddr, '-', err.message);
          try {
            await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
            await db.collection('agentActions').add({
              date: new Date().toISOString().slice(0, 10),
              type: 'imap_failed',
              title: `Inbound email failed to process: ${fromAddr}`,
              summary: `${parsed.subject || '(no subject)'} — ${err.message}`,
              createdAt: new Date().toISOString()
            });
          } catch (_) { /* best-effort dead-letter */ }
          await setLastUid(uid);
        }
      }
    } finally {
      lock.release();
    }
    await client.logout();
  } catch (err) {
    console.error('IMAP poll error:', err.message);
    try { await client.logout(); } catch (_) { /* ignore */ }
  } finally {
    polling = false;
  }
}

function start() {
  if (!env.EMAIL_USER || !env.EMAIL_PASSWORD) {
    console.log('IMAP poller disabled: email credentials not configured');
    return;
  }
  if (env.ENABLE_IMAP_POLLING === 'false') {
    console.log('IMAP poller disabled via ENABLE_IMAP_POLLING=false');
    return;
  }
  console.log(`IMAP poller started (every ${Math.round(POLL_INTERVAL_MS / 1000)}s)`);
  pollOnce();
  timer = setInterval(pollOnce, POLL_INTERVAL_MS);
  timer.unref();
}

module.exports = { start };
