const { ImapFlow } = require('imapflow');
const { simpleParser } = require('mailparser');
const { processInboundEmail } = require('./inboundEmailService');
const { db } = require('../config/firebase');

const POLL_INTERVAL_MS = parseInt(process.env.IMAP_POLL_INTERVAL_MS) || 120000; // 2 minutes
const OWN_ADDRESS = (process.env.EMAIL_FROM || 'hello@superspeech.biz').toLowerCase();

// Never auto-reply to these senders (bounces, self-copies, bots, notifications).
// We email plenty of platform bots ourselves, so this list matters.
const SKIP_SENDER_PATTERNS = [
  'mailer-daemon', 'postmaster', 'no-reply', 'noreply', 'no_reply',
  'pinbot@', 'notifications@', 'notify@', 'auto-confirm', 'automated',
  'security@mail.instagram', 'donotreply', 'bounce', 'newsletter'
];

let timer = null;
let polling = false;

function senderAddress(parsedFrom) {
  if (!parsedFrom) return '';
  const addr = (parsedFrom.value || []).map(a => (a.address || '').toLowerCase()).join(' ');
  return addr || (parsedFrom.text || '').toLowerCase();
}

function shouldSkip(fromAddr) {
  if (!fromAddr) return true;
  if (fromAddr.includes(OWN_ADDRESS)) return true;
  return SKIP_SENDER_PATTERNS.some(p => fromAddr.includes(p));
}

// We track the last processed UID in Firestore rather than relying on the
// \Seen flag - a human (or mail app) opening the inbox marks mail seen and
// would otherwise make the poller skip real customer emails.
async function getLastUid() {
  try {
    const doc = await db.collection('config').doc('imapState').get();
    return doc.exists ? doc.data().lastUid || 0 : null;
  } catch { return null; }
}

async function setLastUid(uid) {
  try {
    await db.collection('config').doc('imapState')
      .set({ lastUid: uid, updatedAt: new Date().toISOString() }, { merge: true });
  } catch (e) { console.warn('imap state write failed:', e.message); }
}

async function pollOnce() {
  if (polling) return;
  polling = true;

  const client = new ImapFlow({
    host: process.env.IMAP_HOST || 'mail.spacemail.com',
    port: parseInt(process.env.IMAP_PORT) || 993,
    secure: true,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASSWORD
    },
    tls: { rejectUnauthorized: false },
    logger: false
  });

  try {
    await client.connect();
    const lock = await client.getMailboxLock('INBOX');
    try {
      let lastUid = await getLastUid();

      // First ever run with no state: seed at the current high-water mark so
      // we don't blast replies at every old email in the box.
      if (lastUid === null) {
        const all = await client.search({ all: true }, { uid: true }) || [];
        const max = all.length ? Math.max(...all) : 0;
        await setLastUid(max);
        console.log(`IMAP poller seeded at UID ${max} (${all.length} existing messages skipped)`);
        return;
      }

      // {uid:true} is essential: without it search returns sequence numbers,
      // not UIDs - expunged mail makes them diverge and we'd process the
      // wrong messages while looping forever on lastUid.
      const uids = await client.search({ uid: `${lastUid + 1}:*` }, { uid: true }) || [];
      for (const uid of uids) {
        const msg = await client.fetchOne(uid, { source: true }, { uid: true });
        if (!msg || !msg.source) { await setLastUid(uid); continue; }

        const parsed = await simpleParser(msg.source);
        const fromAddr = senderAddress(parsed.from);

        // Skip auto-generated messages (out-of-office replies, bounces)
        const autoSubmitted = (parsed.headers.get('auto-submitted') || '').toString().toLowerCase();
        const isAutoGenerated = autoSubmitted && autoSubmitted !== 'no';

        // Self-mail is normally skipped, but a reply to a "[Marketing Agent]"
        // subject from our own address is the owner approving a draft via
        // webmail - let it through so the approval flow can fire.
        const selfAgentReply = fromAddr.includes(OWN_ADDRESS)
          && /re:\s*\[marketing agent\]/i.test(parsed.subject || '');
        if ((shouldSkip(fromAddr) && !selfAgentReply) || isAutoGenerated) {
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          await setLastUid(uid);
          continue;
        }

        try {
          await processInboundEmail({
            from: fromAddr,
            subject: parsed.subject || '',
            text: parsed.text || '',
            html: typeof parsed.html === 'string' ? parsed.html : ''
          });
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          await setLastUid(uid);
          console.log('Processed inbound email from:', fromAddr);
        } catch (err) {
          // Don't advance lastUid - retried on the next poll
          console.error('Failed to process inbound email from', fromAddr, '-', err.message);
        }
      }
    } finally {
      lock.release();
    }
    await client.logout();
  } catch (err) {
    console.error('IMAP poll error:', err.message);
    try { await client.logout(); } catch (_) { /* ignore */ }
  } finally {
    polling = false;
  }
}

function start() {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
    console.log('IMAP poller disabled: email credentials not configured');
    return;
  }
  if (process.env.ENABLE_IMAP_POLLING === 'false') {
    console.log('IMAP poller disabled via ENABLE_IMAP_POLLING=false');
    return;
  }
  console.log(`IMAP poller started (every ${Math.round(POLL_INTERVAL_MS / 1000)}s)`);
  pollOnce();
  timer = setInterval(pollOnce, POLL_INTERVAL_MS);
  timer.unref();
}

module.exports = { start };
