const { ImapFlow } = require('imapflow');
const { simpleParser } = require('mailparser');
const { processInboundEmail } = require('./inboundEmailService');

const POLL_INTERVAL_MS = parseInt(process.env.IMAP_POLL_INTERVAL_MS) || 120000; // 2 minutes
const OWN_ADDRESS = (process.env.EMAIL_FROM || 'hello@superspeech.biz').toLowerCase();

// Never auto-reply to these senders (bounce reports, self-copies, no-reply bots)
const SKIP_SENDER_PATTERNS = ['mailer-daemon', 'postmaster', 'no-reply', 'noreply'];

let timer = null;
let polling = false;

function senderAddress(parsedFrom) {
  if (!parsedFrom) return '';
  const addr = (parsedFrom.value || []).map(a => (a.address || '').toLowerCase()).join(' ');
  return addr || (parsedFrom.text || '').toLowerCase();
}

function shouldSkip(fromAddr) {
  if (!fromAddr) return true;
  if (fromAddr.includes(OWN_ADDRESS)) return true;
  return SKIP_SENDER_PATTERNS.some(p => fromAddr.includes(p));
}

async function pollOnce() {
  if (polling) return;
  polling = true;

  const client = new ImapFlow({
    host: process.env.IMAP_HOST || 'mail.spacemail.com',
    port: parseInt(process.env.IMAP_PORT) || 993,
    secure: true,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASSWORD
    },
    tls: { rejectUnauthorized: false },
    logger: false
  });

  try {
    await client.connect();
    const lock = await client.getMailboxLock('INBOX');
    try {
      const uids = await client.search({ seen: false }) || [];
      for (const uid of uids) {
        const msg = await client.fetchOne(uid, { source: true }, { uid: true });
        if (!msg || !msg.source) continue;

        const parsed = await simpleParser(msg.source);
        const fromAddr = senderAddress(parsed.from);

        // Skip auto-generated messages (out-of-office replies, bounces)
        const autoSubmitted = (parsed.headers.get('auto-submitted') || '').toString().toLowerCase();
        const isAutoGenerated = autoSubmitted && autoSubmitted !== 'no';

        if (shouldSkip(fromAddr) || isAutoGenerated) {
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          continue;
        }

        try {
          await processInboundEmail({
            from: fromAddr,
            subject: parsed.subject || '',
            text: parsed.text || '',
            html: typeof parsed.html === 'string' ? parsed.html : ''
          });
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          console.log('Processed inbound email from:', fromAddr);
        } catch (err) {
          // Leave unread so it is retried on the next poll
          console.error('Failed to process inbound email from', fromAddr, '-', err.message);
        }
      }
    } finally {
      lock.release();
    }
    await client.logout();
  } catch (err) {
    console.error('IMAP poll error:', err.message);
    try { await client.logout(); } catch (_) { /* ignore */ }
  } finally {
    polling = false;
  }
}

function start() {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
    console.log('IMAP poller disabled: email credentials not configured');
    return;
  }
  if (process.env.ENABLE_IMAP_POLLING === 'false') {
    console.log('IMAP poller disabled via ENABLE_IMAP_POLLING=false');
    return;
  }
  console.log(`IMAP poller started (every ${Math.round(POLL_INTERVAL_MS / 1000)}s)`);
  pollOnce();
  timer = setInterval(pollOnce, POLL_INTERVAL_MS);
  timer.unref();
}

module.exports = { start };
